<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends EntityRepository
{
	public function findBySessionId($sess_id)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT t FROM AppBundle:Todo t WHERE t.sessionId = :id ORDER BY t.id ASC'
		);
        $query->setParameter('id', $sess_id);
        return $query->getResult();
    }
    
    public function findCompleted($sess_id)
    {
    	$query = $this->getEntityManager()->createQuery(
            'SELECT t FROM AppBundle:Todo t WHERE t.sessionId = :id AND t.completed = :completed ORDER BY t.id ASC'
		);
        
        $query->setParameter('id', $sess_id)
			->setParameter('completed', 1);
        return $query->getResult();
    }
    
    public function findActive($sess_id)
    {
    	$query = $this->getEntityManager()->createQuery(
            'SELECT t FROM AppBundle:Todo t WHERE t.sessionId = :id AND t.completed = :completed ORDER BY t.id ASC'
		);
        
        $query->setParameter('id', $sess_id)
			->setParameter('completed', 0);
        return $query->getResult();
    }
   
}